baseURL = 'https://lllama.github.io/'
languageCode = 'en-gb'
theme = "hugo-theme-m10c"
title = "Lllama's blog"

[params]
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright lllama. All rights reserved."

